export const actionConstants = {

  // STARTED
  SIGN_IN_STARTED: 'SIGN_IN_STARTED',
  SIGN_UP_STARTED: 'SIGN_UP_STARTED',
  SIGN_OUT_STARTED: 'SIGN_OUT_STARTED',
  GET_USER_STARTED: 'GET_USER_STARTED',
  EDIT_USER_STARTED: 'EDIT_USER_STARTED',
  GET_CATALOG_STARTED: 'GET_CATALOG_STARTED',
  PAYMENT_STARTED: 'PAYMENT_STARTED',
  CARD_SAVE_STARTED: 'CARD_SAVE_STARTED',
  
  
  
  
  //ERROR
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  GET_USER_ERROR: 'GET_USER_ERROR',
  EDIT_USER_ERROR: 'EDIT_USER_ERROR',
  GET_CATALOG_ERROR: 'GET_CATALOG_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  CARD_SAVE_ERROR: 'CARD_SAVE_ERROR',
  
  
  
  //SUCCESS
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  CART_CHANGE_SUCCESS: 'CART_CHANGE_SUCCESS',
  GET_CATALOG_SUCCESS: 'GET_CATALOG_SUCCESS',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  CARD_SAVE_SUCCESS: 'CARD_SAVE_SUCCESS',

  

};
